app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('extensions/', include('extensions.urls')),
    path('elp/', include('extensions.urls')),
    path('accounts/', include('accounts.urls')),
    path('projects/', include('projects.urls')),
    path('', include('front.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

app/projects/urls.py
from django.urls import path
from django.contrib import admin

admin

from . import views

app_name = 'projects'

urlpatterns = [
    #path("", views.index, name="index"),
    path("", views.returning_staff, name="returning-staff"),
    path("back/", views.back, name="back"),
    path("SVS", views.SVS, name="SVS"),
    path("staff_details/", views.staff_details, name="staff-details"),
    path("project_details/", views.project_details, name="project-details"),
    path("returning_staff/", views.returning_staff, name="returning-staff"),
    #path("staff_thanks/", views.staff_thanks, name="staff-thanks"),
    path("student_thanks/", views.student_thanks, name="student-thanks"),
    #path("download/", projects.views.download, name='download'),
    #path("download_student/", views.download_student, name='downlaod-student'),
    #path("download_staff/", projects.views.download_staff, name='download-staff'),
    #path("iacd_download/", projects.views.iacd_download, name='iacd-download'),
    path("student/svs", views.student, name='student'),
    path("student/", views.student, name='student'),
    path("<str:school>/student/", views.student, name='student'),
    path("tandc/", views.tandc, name='tandc'),
    path("privacy/", views.privacy, name='privacy'),
    #path("keywords_list/", projects.views.keywords_list, name='keywords-list'),
    #path("area_list/", projects.views.area_list, name='area-list'),
    #path("type_list/", projects.views.type_list, name='type-list'),
    path("staff_project/", views.staff_project, name='staff-project'),
    path("use_again/<id>", views.use_again, name='use-again'),
    path("edit_project/<id>", views.edit_project, name='edit-project'),
    path("admin/", admin.site.urls),
]

app/projects/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.db import IntegrityError
import os
from itertools import chain
from .models import Staff, Project, ProjectKeyword, Student, ProjectArea, ProjectType
from .forms import StaffForm, ProjectForm, ExistingStaffForm, StudentForm
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta
today = datetime.now().date() - timedelta(days=100)
from accounts.models import Department

INSTITUTE = (
        ('1', 'Ageing and Chronic Disease'),
        ('2', 'Human Anatomy Resource Centre'),
        ('3', 'Infection and Global Health'),
        ('4', 'Integrative Biology'),
        ('5', 'Liverpool School of Tropical Medicine'),
        ('6', 'School of Life Sciences'),
        ('7', 'Translational Medicine'),
        ('8', 'Other'),
    )
DEPARTMENT = (
        ('1', 'Eye and Vision Science'),
        ('2', 'Musculoskeletal Biology I'),
        ('3', 'Musculoskeletal Biology II'),
        ('4', 'Clinical Infection, Microbiology and Immunology'),
        ('5', 'Epidemiology and Population Health'),
        ('6', 'Infection Biology'),
        ('7', 'Biochemistry'),
        ('8', 'Evolution, Ecology and Behaviour'),
        ('9', 'Funtional and Comparative Genomics'),
        ('10', 'Clinical Sciences'),
        ('11', 'International Public Health'),
        ('12', 'Parasitology'),
        ('13', 'Vector Biology'),
        ('14', 'Biostatistics'),
        ('15', 'Cellular and Molecular Physiology'),
        ('16', 'Molecular and Clinical Cancer Medicine'),
        ('17', 'Molecular Pharmacology'),
        ('18', "Women's and Children's Health"),
        ('19', "Not applicable (SOLS, HARC etc)"),
        ('20', "Other"),
    )

def index(request):
    return render(request, 'projects/index.html')

def SVS(request):
    return render(request, 'projects/SVS-index.html')

def returning_staff(request):

    if request.method == "POST":


        form = ExistingStaffForm(request.POST)
        if form.is_valid():
            staff = Staff.objects.get(username=form.cleaned_data['username'])
            print("STAFF", staff)
            projects = Project.objects.filter(staff=staff).order_by("-pk")#distinct("title", "active")


            existing_staff_form = ExistingStaffForm()
            existing_staff_form['username'].initial = staff.username

            return render(request, "projects/staff_dash.html", {'projects': projects,
                                                        'form': existing_staff_form,
                                                        'staff': staff})


    else:
        form = ExistingStaffForm()


    return render(request, "projects/returning-staff.html", {'form': form})


def staff_project(request):

    if request.method == "POST":

        form = ExistingStaffForm(request.POST)

        if form.is_valid():
            staff = Staff.objects.get(username=form.cleaned_data['username'])
            staff.username = staff.username.lower()
            project_form = ProjectForm(staff=staff)
            project_form['staff'].initial = staff
            print("Hello World!")
            return render(request, "projects/project.html", {'form': project_form,
                                                     'staff': staff})

    else:
        form = StaffForm()

    return render(request, "staff.html", {'form': form})


def project_details(request):

    if request.method == "POST":
        staff = Staff.objects.get(pk=int(request.POST["staff"]))

        form = ProjectForm(request.POST, staff=staff)
        form['staff'].initial = staff

        print("CHECKING FORM IS VALID")


        if form.is_valid():
            print("FORM IS VALID !!!!!!")
            staff = form.cleaned_data["staff"]

            inst = form.save()
 

            projects = Project.objects.filter(staff=staff)
            staff = Staff.objects.get(id=staff.id)

            existing_staff_form = ExistingStaffForm()
            existing_staff_form['username'].initial = staff.username
            return render(request, "projects/staff_dash.html", {"form": existing_staff_form,
                                                       "projects": projects,
                                                       "staff": staff})
        else:
            print(form.errors)
            print(form.non_field_errors())
            return render(request, "projects/project.html", {"form": form,
                                                     "staff": staff})



def use_again(request, id):

    try:
        project = Project.objects.get(pk=id)
    except:
        return redirect('index')
    form = ProjectForm(instance=project, staff=project.staff)

    return (render(request, "projects/project.html", {"form": form,
                                              "flag": True}))


def edit_project(request, id):

    try:
        project = Project.objects.get(id=id)
        staff = Staff.objects.get(id=project.staff.id)
    except:
        return redirect('/projects/index')

    if request.method == "POST":
        print("I'M POSTING")
        form = ProjectForm(request.POST or None, instance=project, staff=staff)
        if form.is_valid():
            form.save()
            projects = Project.objects.filter(staff=staff)

            existing_staff_form = ExistingStaffForm()
            existing_staff_form['username'].initial = staff.username
            return render(request, "projects/staff_dash.html", {"form": existing_staff_form,
                                                        "projects": projects,
                                                        "staff": staff})
        else:
            form.add_error(None, "You have chosen too many/too few keywords or other types of project. Your project has not been saved. Make changes and click 'Submit'.")
            return render(request, "projects/edit_project.html", {"form": form,
                                                         "staff": staff,
                                                         "project": id})

    form = ProjectForm(instance=project, staff=staff)


    return render(request, "projects/edit_project.html", {"form": form,
                                                  "staff": staff,
                                                  "project": id})


def staff_details(request):

    if request.method == "POST":
        form = StaffForm(request.POST)
        if form.is_valid():
            form.save()
            staff = Staff.objects.get(username=form.cleaned_data['username'])
            staff.username = staff.username.lower()
            project_form = ProjectForm(staff=staff)
            project_form['staff'].initial = staff
            return render (request, "projects/project.html", {'form': project_form,
                                                      'staff': staff})

    else:
        form = StaffForm()

    return render(request, "projects/staff.html", {'form': form})


def tandc(request):
    return render(request, "projects/terms_and_conditions.html")

def privacy(request):

    return render(request, "projects/privacy_policy.html")

def check_unique_set(request, key):

    obj_list = [request.POST["{0}_{1}".format(key, x)] for x in range(1, 6)]

    if len(set(obj_list)) < 5:
        print(len(set(obj_list)))
        return False

    print(len(set(obj_list)))

    return True

def student(request, school=None):


    print("Printing school", school)

    if school:
        # make school all upper case
        school = school.upper()
        department = Department.objects.get(label=school)
        #department = Department.objects.get(label=school)
    else:
        department = Department.objects.get(label="SOLS")

    print("SCHOOL", school)
    
    if request.method == "POST":
        print("GOT HERE")


        form = StudentForm(request.POST, school=department)

        print("Keywords Unique", check_unique_set(request, "project_keyword"))
        print("Types Unique", check_unique_set(request, "project_type"))


        if check_unique_set(request, "project_keyword") and check_unique_set(request, "project_type"):
            print("I'm getting through the unique check")

            

            if form.is_valid():
                print("form is valid!")
                try:
                    # create instance of form without saving
                    inst = form.save(commit=False)
                    inst.school = department
                    inst.save()
                    print(inst.school)
                
                except IntegrityError:
                    form.add_error(None, "UNIQUE")



                return redirect('projects:student-thanks')
            
            print("form is not valid!")
            print(form.errors)

        else:
            print("form is not valid!")

            form.add_error(None, "Error")

            return render(request, "projects/student_form.html", {"form": form})

    else:

        form = StudentForm(school=department)

    return render(request, "projects/student_form.html", {"form": form})



def student_thanks(request):

    return render(request, "projects/student_thanks.html")

def back(request):
    url = request.META.get('HTTP_REFERER')

    # remove last part of url
    url = url.rsplit('/', 2)[0]
    

    return HttpResponseRedirect(url)

app/projects/templates/projects/SVS-index.html
{% extends "projects/base.html" %}
{% load static %}

{% block content %}

<div class="jumbotron text-center">
  <div class="container">
    <h1>SoVS Supervisor Allocation</h1>
    <p>A web app to automate Honours project allocation in the School of Veterinary Science, University of Liverpool.</p>
    <a href="{% url 'projects:returning-staff' %}">
      <button class="btn btn-lg btn-secondary">Staff Questionnaire</button>
    </a>
    
    <!--<a href="SVS/student/">-->
    
    <button class="btn btn-lg btn-primary"> Submit Preferences (Students)</button>
    <!--</a>-->
  </div>
</div>
<div class="container info">

  <div class="alert alert-info text-center" role="alert">
    Staff can now submit their projects for 2023/24 (click above).
  </div>

  <hr>
  <div class="container info">
    <div class="row">
      <div class="col-md-6">
        <h3><span class="glyphicon glyphicon-info-sign"></span>  How does this web app work?</h3>
        <p>This online webapp replaces a pre-existing manual allocation process.</p>
        <ul>
          <li>Students submit their preferences for <b>project area keywords</b> and <b>project types</b>.</li>
          <li>An automated allocation algorithm works to optimise matches based on the preferences of <b>all</b> students.</li>
        </ul>
      </div>
      <div class="col-md-6">
        <h3><span class="glyphicon glyphicon-star"></span>  Improvements</h3>
        <ul>
          <li>Staff can now keep track of projects that they have submitted.</li>
          <li>Staff can re-submit previous projects with any necessary edits.</li>
          <li>All staff will be allocated at least one project.</li>
          <li>Unhappy with your allocated project? You can <a href="mailto:A.D.Radford@liverpool.ac.uk">request a re-allocation</a>.</li>
          </ul>
        </ul>
      </div>
    </div> <!-- row -->
  </div>

  <div class="container info">
    <div class="row">
      <div class="col-md-6">
        <h3><span class="glyphicon glyphicon-question-sign"></span>  Why can't I see a list of project titles?</h3>
        <p>In pevious years students submitted a long prioritised preference list for projects based on project titles and descriptions.
        This meant that only very few students received their first (or even second, third fourth or fifth) choice of project.
        Now, by allowing you to prioritise based on project area keywords and project types alone it is much more likely that you will be allocated a project that will meet your preferences.</p>
      </div>
      <div class="col-md-6">
        <h3><span class="glyphicon glyphicon-warning-sign"></span>  Project allocation myths.</h3>
        <ul>
          <li>Students with higher average grades are more likely to be allocated their first choice of project type and area.</li>
          <li>Projects are allocated on a first come first serve basis.</li>
          <li>Staff are able to allocate projects to students independently of this automated process.</li>
          </ul>
        </ul>
      </div>
    </div> <!-- row -->
  </div>
  <hr>
  <!--
  <div class="alert alert-info text-center" role="alert">
    Last year <b>70%</b> of students got their first choice of project area or project type.
  </div>
    -->

</div>

{% endblock %}

app/projects/templates/projects/base.html
<!DOCTYPE html>
<html>
<head>
  <title>SoLS Project Allocation</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="Robert Treharne">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <style type="text/css">


    .jumbotron {
        background: #532f8c;
        color: white;
        padding-bottom: 80px;
           border-radius: 0px;
    }
    .jumbotron .btn {
        margin: 10px;
        width: 100%;
        max-width: 250px;
        font-size: 1em;
    }
    .jumbotron .btn-primary, .btn-primary {
        background: #845ac7;
        border-color: #845ac7

    }
    .jumbotron .btn-primary:hover {
        background: #7646c1;

    }
    .jumbotron p {
        color: #d9ccee;
        max-width: 75%;
        margin: 1em auto 2em
    }
    .navbar+.jumbotron {
        margin-top: -20px
    }
    .jumbotron .lang-logo {
        display: block;
        background: #b01302;
        border-radius: 50%;
        overflow: hidden;
        width: 100px;
        height: 100px;
        margin: auto;
        border: 2px solid white
    }
    .jumbotron .logo img {
        max-width: 100px;
        margin: 20px;
    }

    p, ul {
      font-size: 18px;
    }
    .info {
      margin-bottom: 20px;
      margin-top: 20px;
    }

    .btn-submit {
      float: right;
    }

    footer {
      height: 100px;
      background-color: #444;
      color: #fff;
    }

    .aligner {
      display: flex;
      align-items: center;
      justify-content: center;
    }

    #div_id_staff {
        display: visible;
    }
    form input, select, textarea {
        width: 100%;
        margin-bottom: 20px;
        height: 50px;
        padding: 10px;
    }

    form button, input.btn {
        width: 250px;
    }

    select[name="other_type"], select[name="modules"] {
        height: 300px;
    }
    input[type="checkbox"] {
        width: 20px;
        height: 20px;
    }

    label {
        font-weight: bold;
        font-size: 1.1em;
    }
    .alert {
        font-weight: bold;
        color: red
    }


  </style>
</head>
<body>
<!--
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container ">
    <ul class="nav navbar-nav">
      <li class="active">
        <a href="/"><span class="glyphicon glyphicon-home"></span> Home</a>
      </li>
      <li>
        <a href="https://devcenter.heroku.com/articles/how-heroku-works"><span class="glyphicon glyphicon-user"></span> How Heroku Works</a>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-info-sign"></span> Getting Started Guides <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-ruby">Getting Started with Ruby on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-nodejs">Getting Started with Node on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-php">Getting Started with PHP on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-python">Getting Started with Python on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-java">Getting Started with Java on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-clojure">Getting Started with Clojure on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-scala">Getting Started with Scala on Heroku</a></li>
            <li class="divider"></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-heroku-and-connect-without-local-dev">Getting Started on Heroku with Heroku Connect</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-jruby">Getting Started with Ruby on Heroku (Microsoft Windows)</a></li>
          </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="navbar-right">
        <a href="https://devcenter.heroku.com"><span class="glyphicon glyphicon-book"></span> Heroku Dev Center</a>
      </li>
    </ul>
  </div>
</nav>
-->

{% block content %}{% endblock %}

<footer class="containter text-center aligner">
  <div>
    &copy School of Life Sciences TEL Team 2023 | <a href="/projects/tandc">Terms and Conditions</a> | <a href="/projects/privacy">Privacy Policy</a>
  </div>
</footer>

</body>
</html>

app/projects/templates/projects/edit_project.html
{% extends "projects/base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

<style>

    select[name="project_keyword"] {
        height: 300px;
    }
    textarea {
        height: 150px;
    }

    #div_id_iacd_area, #div_id_iacd_training, #div_id_iacd_techniques, #div_id_iacd_area_other, #div_id_iacd_supervisor_2 {
        display: none;
    }

    #div_id_suggested_keyword {
        display: none;
    }

</style>

<div class="jumbotron text-center">
  <div class="container">
    <h1>Edit Project</h1>

    <p>Please make any desired changes to this project and click "Submit" at the bottom of the page.</p>


      {% if form.errors %}
      <p><b>There was an error in the form below. Please check.</b></p>
      {% endif %}
  </div>
</div>
<div class="container info">
  <div class="row">
    <div class="offset-md-3 col-md-6">

      <form action="/projects/edit_project/{{ project }}" method="post">
          {% csrf_token %}
          {{ form |crispy}}
        <a href="javascript:history.back()">
            <button type="button" class="btn btn-lg btn-secondary">Cancel</button>
          </a>
          <input class="btn btn-primary btn-lg btn-submit" type="submit" value="Submit" />
      </form>

    </div>
  </div>
</div>

{% endblock %}

app/projects/templates/projects/index.html
{% extends "projects/base.html" %}
{% load static %}

{% block content %}

<div class="jumbotron text-center">
  <div class="container">
    <h1>SoLS Project Allocation</h1>
    <p>A web app to automate Honours project allocation in the School of Life Sciences, University of Liverpool.</p>
    <a href="{% url 'projects:returning-staff' %}">
      <button class="btn btn-lg btn-secondary">Submit Project (Staff)</button>
    </a>
    <a href="{% url 'projects:student' %}">
    <button class="btn btn-lg btn-primary"> Submit Preferences (Students)</button>
    </a>
  </div>
</div>
<div class="container info">

  <div class="alert alert-info text-center" role="alert">
    Staff can now submit their projects for 2023/24 (click above).
  </div>

  <hr>
  <div class="container info">
    <div class="row">
      <div class="col-md-6">
        <h3><span class="glyphicon glyphicon-info-sign"></span>  How does this web app work?</h3>
        <p>This online webapp replaces a pre-existing manual allocation process.</p>
        <ul>
          <li>Students submit their preferences for <b>project area keywords</b> and <b>project types</b>.</li>
          <li>An automated allocation algorithm works to optimise matches based on the preferences of <b>all</b> students.</li>
          <li>Students and staff will receive automatic notifications of allocations in <b>early October 2023</b>.</li>
          <li>Last year 70% of students were allocated their first choice of project area.</li>
        </ul>
      </div>
      <div class="col-md-6">
        <h3><span class="glyphicon glyphicon-star"></span>  Improvements</h3>
        <ul>
          <li>Staff can now keep track of projects that they have submitted.</li>
          <li>Staff can re-submit previous projects with any necessary edits.</li>
          <li>Allocations will now consider only a single second year pre-requisite.</li>
          <li>All staff will be allocated at least one project.</li>
          <li>Unhappy with your allocated project? You can <a href="mailto:bates@liverpool.ac.uk">request a re-allocation</a>.</li>
          </ul>
        </ul>
      </div>
    </div> <!-- row -->
  </div>

  <div class="container info">
    <div class="row">
      <div class="col-md-6">
        <h3><span class="glyphicon glyphicon-question-sign"></span>  Why can't I see a list of project titles?</h3>
        <p>In pevious years students submitted a long prioritised preference list for projects based on project titles and descriptions.
        This meant that only very few students received their first (or even second, third fourth or fifth) choice of project.
        Now, by allowing you to prioritise based on project area keywords and project types alone it is much more likely that you will be allocated a project that will meet your preferences.</p>
      </div>
      <div class="col-md-6">
        <h3><span class="glyphicon glyphicon-warning-sign"></span>  Project allocation myths.</h3>
        <ul>
          <li>Students with higher average grades are more likely to be allocated their first choice of project type and area.</li>
          <li>Projects are allocated on a first come first serve basis.</li>
          <li>Staff are able to allocate projects to students independently of this automated process.</li>
          </ul>
        </ul>
      </div>
    </div> <!-- row -->
  </div>
  <hr>
  <div class="alert alert-info text-center" role="alert">
    Last year <b>70%</b> of students got their first choice of project area or project type.
  </div>

</div>

{% endblock %}

app/projects/templates/projects/project.html
{% extends "projects/base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

<style>
    select[name="project_keyword"] {
        height: 300px;
    }
    textarea {
        height: 150px;
    }

    #div_id_iacd_area, #div_id_iacd_training, #div_id_iacd_techniques, #div_id_iacd_area_other, #div_id_iacd_supervisor_2 {
        display: none;
    }

    #div_id_suggested_keyword {
        display: none;
    }

    [id*="error"] {
      color: red;
    }
    
</style>

<div class="jumbotron text-center">
  <div class="container">
    <h1>Your Interests</h1>
    <h3>Submit a new preference set</h3>

    {% if flag  %}
      <p>Please make any desired changes to this project and click "Submit" at the bottom of the page.</p>
    {% else %}


     {% endif %}

      {% if form.errors %}
      <p><b>There was an error in the form below. Please check.</b></p>
      {% endif %}
  </div>
</div>
<div class="container info">
  <div class="row">
    <div class="offset-md-3 col-md-6">

      <form action="/projects/project_details/" method="post">
          {% csrf_token %}
          {{ form |crispy}}
          <a href="javascript:history.back()">
            <button type="button" class="btn btn-lg btn-secondary">Cancel</button>
          </a>
          <input class="btn btn-primary btn-lg btn-submit" type="submit" value="Submit" />
      </form>

    </div>
  </div>
</div>

{% endblock %}

app/projects/templates/projects/projects_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
    <a href="import-csv/">Import from CSV</a>
    <a href="update-csv/">Update from CSV</a>
    <br />
    {{ block.super }}
{% endblock %}

app/projects/templates/projects/returning-staff.html
{% extends "projects/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="jumbotron text-center">
  <div class="container">
    <h1>Supervisor Allocation System</h1>
    <h3>Staff Portal</h3>
    <p>Enter your MWS username and proceed to add another project description.</p>
  </div>
</div>
<div class="container info">
  <div class="row">
    <div class="offset-md-3 col-md-6">
        <div class="alert alert-info text-center" role="alert">
         <b>Is this is the first time you have used this system? If so, please click
             <a href="{% url 'projects:staff-details' %}">here</a> to register your details</b>.
      </div>
      <form action="" method="post">
          {% csrf_token %}
          {{ form|crispy }}

          <input style="width:100%" class="btn btn-primary btn-lg btn-submit" type="submit" value="Submit" />
      </form>

    </div>
  </div>
</div>

{% endblock %}

app/projects/templates/projects/staff.html
{% extends "projects/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="jumbotron text-center">
  <div class="container">
    <h1>Staff Details</h1>
    <p>Enter your details before submitting your projects.</p>
      {% if form.errors %}
      <p><b>There was an error in the form below. Please check.</b></p>
      {% endif %}
  </div>
</div>
<div class="container info">
  <div class="row">
    <div class="offset-md-3 col-md-6">
    <div class="alert alert-info text-center" role="alert">
        Already filled in your details?
        <br>
        <b>Click <a href="{% url 'projects:returning-staff' %}">here</a> to add keywords and preferences.</b>
     </div>

      <form action="" method="post">
          {% csrf_token %}
          {{ form|crispy }}
                    <a href="javascript:history.back()">
            <button type="button" class="btn btn-lg btn-secondary" href="javascript:history.back()">Cancel</button>
          </a>
          <input class="btn btn-primary btn-lg btn-submit" type="submit" value="Submit" />
      </form>

    </div>
  </div>
</div>

{% endblock %}

app/projects/templates/projects/staff_dash.html
{% extends "projects/base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

<style>
    select[name="project_keyword"] {
        height: 300px;
    }
    textarea {
        height: 150px;
    }

    #div_id_iacd_area, #div_id_iacd_training, #div_id_iacd_techniques, #div_id_iacd_area_other, #div_id_iacd_supervisor_2 {
        display: none;
    }

    #div_id_suggested_keyword {
        display: none;
    }




    .right {
        text-align: right;

    }

</style>

<div class="jumbotron text-center">
  <div class="container">
    <h1>My Preferences</h1>
    <a href="{% url 'projects:returning-staff' %}">Back</a>
    <p>Here is a list of your past and preference sets</p>
      {% if form.errors %}
      <p><b>There was an error in the form below. Please check.</b></p>
      {% endif %}
  </div>
</div>
<div class="container info">
  <div class="row">
    <div class="offset-md-3 col-md-6">


      {% for project in projects %}
        <!--{% if project.active %}-->
      <div class="row">
      <div class="col-lg-9">


         
          <p >
              <b>Cognate Area:</b> {{ project.project_area }}
          </p>
          <p >
              <b>Keywords:</b>
              {% for keyword in project.project_keyword.all %}{{ keyword }} | {% endfor %}
          </p>

      </div>
      <div class="right col-lg-3">
          <a href="/projects/edit_project/{{ project.id }}">
              <button type="button" class="btn btn-danger">Edit</button>
          </a>
      </div>
      </div>

      <hr>
        <!--{% endif %}-->
      {% endfor %}


      <form action="{% url 'projects:staff-project' %}" method="post">
          {% csrf_token %}
          <input style="width: 100%" class="btn btn-primary btn-lg btn-submit" type="submit" value="Submit New Preference Set" />
          <div class="invisible">
          {{ form|crispy }}
          </div>

      </form>

      <h2>Past Projects</h2>
        <div class="alert alert-info text-center" role="alert">
    You can click "Use Again" to re-submit any previous project. You WILL be able
         to edit the project before confirming submission.
  </div>

        <br>
      {% for project in projects %}
        {% if not project.active %}
      <div class="row">
      <div class="col-lg-9">
          <h4>{{ project.title }}</h4>
          <p>{{ project.description }}</p>
      </div>
      <div class="right col-lg-3">
          <a href="/projects/use_again/{{ project.id }}">
              <button type="button" class="btn btn-secondary">Use Again</button>
          </a>
      </div>
      </div>

      <hr>
        {% endif %}
      {% endfor %}




    </div>
  </div>
</div>


{% endblock %}