app/accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView, LoginView

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(redirect_authenticated_user=True)),
    path('', include("django.contrib.auth.urls")),
    path('register/', views.register_user, name='register'),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('extensions/', include('extensions.urls')),
    path('elp/', include('extensions.urls')),
    path('accounts/', include('accounts.urls')),
    path('projects/', include('projects.urls')),
    path('', include('front.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

app/core/urls.py
from django.urls import path, include

from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index(), name='index'),
]

app/core/models.py
from django.db import models
from accounts.models import Department

class Sample(models.Model):
    attachment = models.FileField()

class AssignmentType(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

class Course(models.Model):
    course_code = models.CharField(max_length=128, unique=True)
    course_id = models.IntegerField(null=True, blank=True, unique=True)
    course_name = models.CharField(max_length=128)
    course_department = models.ForeignKey(Department, null=True, blank=True, on_delete=models.PROTECT)
    resit_course = models.ForeignKey('self', null=True, blank=True, on_delete=models.PROTECT)
    active = models.BooleanField(default=True, verbose_name="Active Flag")
    programme = models.ManyToManyField('Programme', blank=True)
        
    def __str__(self):
        return self.course_code
    
    
class Assignment(models.Model):
    department = models.ForeignKey(Department, null=True, blank=True, on_delete=models.PROTECT)
    assignment_name = models.CharField(max_length=500, verbose_name="Assignment")
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    points_possible = models.FloatField(null=True, blank=True)
    assignment_id = models.IntegerField(unique=True)
    unlock_at = models.DateTimeField(null=True, blank=True)
    lock_at = models.DateTimeField(null=True, blank=True)
    due_at = models.DateTimeField(null=True, blank=True, verbose_name="Deadline")
    url = models.URLField()
    needs_grading_count = models.IntegerField(null=True, blank=True)
    published = models.BooleanField(null=True, blank=True, verbose_name="Published")
    anonymous_grading = models.BooleanField(verbose_name="Anonymous Grading")
    active = models.BooleanField(default=True, verbose_name="Active Flag")
    graded = models.IntegerField(null=True, blank=True, default=0)
    ungraded = models.IntegerField(null=True, blank=True, default=0)
    pc_graded = models.FloatField(null=True, blank=True, verbose_name="Graded (%)", default=0)
    not_submitted = models.IntegerField(null=True, blank=True,default=0)
    quiz = models.BooleanField(default=False, verbose_name="Quiz")
    sas_exam = models.BooleanField(default=False, verbose_name="SAS Exam")
    average_score = models.FloatField(null=True, blank=True, verbose_name="Average Score (%)")
    type = models.CharField(max_length=128, null=True, blank=True)
    has_overrides = models.BooleanField(default=False, verbose_name="Overrides")
    posted_at = models.DateTimeField(null=True, blank=True)
    rollover_to_course = models.ForeignKey(Course, null=True, blank=True, on_delete=models.PROTECT, related_name="rollover_to_course")
    previous_term_assignment = models.ForeignKey('self', null=True, blank=True, on_delete=models.PROTECT)
    assignment_type = models.ForeignKey(AssignmentType, null=True, blank=True, on_delete=models.PROTECT)
    rubric_title = models.CharField(max_length=128, null=True, blank=True)

    def __str__(self):
        return self.assignment_name

class Programme(models.Model):
    name = models.CharField(max_length=128)
    code = models.CharField(max_length=128, null=True, blank=True)

    def __str__(self):
        return self.name

class Student(models.Model):
    sortable_name = models.CharField(max_length=128, verbose_name="Student Name")
    programme = models.ForeignKey(Programme, null=True, blank=True, on_delete=models.CASCADE)
    sis_user_id = models.CharField(max_length=256, null=True, blank=True)
    canvas_id = models.IntegerField(unique=True)
    login_id = models.EmailField(null=True, blank=True)
    support_plan = models.BooleanField(default=False, verbose_name="SpLD")
    repeating = models.BooleanField(default=False, verbose_name="Repeating")
    marker_message = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.sortable_name
    
class Submission(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    sis_user_id = models.CharField(max_length=128, null=True, blank=True)
    submission_id = models.IntegerField()
    submitted_at = models.DateTimeField(null=True, blank=True)
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, null=True, blank=True, on_delete=models.CASCADE)
    score = models.FloatField(null=True, blank=True)
    posted_at = models.DateTimeField(null=True, blank=True)
    graded_by = models.CharField(max_length=286, null=True, blank=True)
    seconds_late = models.IntegerField(default=0)
    late = models.BooleanField(default=False)
    excused = models.BooleanField(default=False, null=True, blank=True)
    comments = models.TextField(null=True, blank=True)
    rubric = models.TextField(null=True, blank=True)
    similarity_score = models.FloatField(null=True, blank=True)
    turnitin_url = models.URLField(null=True, blank=True)
    integrity_concern = models.CharField(max_length=128, null=True, blank=True, default=None, verbose_name="Integrity Flag")
    gai_declaration = models.CharField(max_length=128, null=True, blank=True, default=None, verbose_name="GAI Declaration")
    html_url = models.URLField(null=True, blank=True)
    marker = models.CharField(max_length=256, null=True, blank=True)
    marker_email = models.EmailField(null=True, blank=True)
    
    def __str__(self):
        return self.student.sortable_name

class Staff(models.Model):
    name = models.CharField(max_length=128)
    canvas_id = models.IntegerField(null=True, blank=True, unique=True)
    items_graded = models.IntegerField(null=True, blank=True)
    courses_graded_in = models.IntegerField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Staff"

    def __str__(self):
        return self.name
    
class Date(models.Model):
    label = models.CharField(max_length=128)
    start = models.DateField(null=True, blank=True)
    finish = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.label








    

app/core/forms.py
from django import forms
from .models import Assignment, Course

class CsvImportForm(forms.Form):
    csv_file = forms.FileField()

    # Add validation. Must be .csv file
    def clean_csv_file(self):
        csv_file = self.cleaned_data['csv_file']
        if not csv_file.name.endswith('.csv'):
            print("File is not a .csv file")
            raise forms.ValidationError('Please upload a .csv file')
        return csv_file


from django.forms.widgets import DateInput, TimeInput


class AssignmentDatesUpdateForm(forms.Form):
    unlock_date = forms.DateField(
        required=False,
        widget=DateInput(
            attrs={'type': 'date', 'class': 'form-control'}
        )
    )

    unlock_time = forms.DateField(
        required=False,
        widget=TimeInput(
            attrs={'type': 'time', 'class': 'form-control'}
        )
    )

    deadline_date = forms.DateField(
        required=False,
        widget=DateInput(
            attrs={'type': 'date', 'class': 'form-control'}
        )
    )

    deadline_time = forms.DateField(
        required=False,
        widget=TimeInput(
            attrs={'type': 'time', 'class': 'form-control'}
        )
    )

    lock_date = forms.DateField(
        required=False,
        widget=DateInput(
            attrs={'type': 'date', 'class': 'form-control'}
        )
    )

    lock_time = forms.DateField(
        required=False,
        widget=TimeInput(
            attrs={'type': 'time', 'class': 'form-control'}
        )
    )

    only_visible_to_overrides = forms.BooleanField(initial=False, required=False)



    




class AssignResitForm(forms.Form):
    """
    Create a form to select a course.
    Order the queryset by course_code, alphabetially.
    """

    resit_course = forms.ModelChoiceField(queryset=Course.objects.all().order_by('course_code'), empty_label=None)

app/core/views.py
from django.shortcuts import render


def index(request):
    return render(request, "core/index.html")

app/core/templates/core/assign_resit_course_form.html
{% extends 'admin/base.html' %}

{% block content %}
    <div>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p style="color: red;">Are you sure you want to execute this action on the selected items? This cannot be undone.</p>
            {% for course in courses %}
            <strong>
                {{ course.pk}} - {{ course }}</br>
            </strong>
            <input type="hidden" name="_selected_action" value="{{ course.pk }}" />
            {% endfor %}

            </br>
            
            <input type="hidden" name="action" value="assign_resit_course" />
            <input type="submit" name="apply" value="Update Courses"/>

        </form>
    </div>
    <br />

{% endblock %}

app/core/templates/core/assignment_dates_update_form.html
{% extends 'admin/base.html' %}

{% block content %}
    <div>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p style="color: red;">Are you sure you want to execute this action on the selected items? This cannot be undone.</p>
            {% for assignment in assignments %}
            <strong>
                {{ assignment }}: {{ assignment.course }}</br>
            </strong>
            <input type="hidden" name="_selected_action" value="{{ assignment.pk }}" />
            {% endfor %}

            </br>
            
            <input type="hidden" name="action" value="update_assignment_deadlines" />
            <input type="submit" name="apply" value="Update Assignments"/>

        </form>
    </div>
    <br />

{% endblock %}

app/core/templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Prof. Joe Bloggs">
    <meta name="generator" content="JB">
    <title>Canvas Lens</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/starter-template/">





<link href="https://getbootstrap.com/docs/5.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">




    <style>

      body:after{
        content: "beta";
        position: fixed;
        width: 80px;
        height: 25px;
        background: #EE8E4A;
        top: 7px;
        left: -20px;
        text-align: center;
        font-size: 13px;
        font-family: sans-serif;
        text-transform: uppercase;
        font-weight: bold;
        color: #fff;
        line-height: 27px;
        transform:rotate(-45deg);
      }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/5.3/examples/starter-template/starter-template.css" rel="stylesheet">
  </head>
  <body>


<div class="col-lg-8 mx-auto p-4 py-md-5">

  <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
    
    <a href="/" class="d-flex  text-dark text-decoration-none">
        

      <span class="fs-4">New Webapp</span>
      
    </a>
  </header>

  {% if user.is_authenticated %}
    <p>User: {{user.username}} | <a href="{% url 'accounts:logout' %}">Logout</a></p>
  {% else %} 
    <p><a href="/accounts/login/">Login</a> | <a href="{% url 'accounts:register' %}">Register</a></p>
  {% endif %}

  <main>
    {% block content %}
    {% endblock %}
  </main>
  <footer class="pt-5 my-5 text-muted border-top">
    Created by <a href="mailto:">Prof. Joe Bloggs</a>&middot; &copy; 2023
  </footer>
</div>


    <script src="https://getbootstrap.com/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>


  </body>
</html>

app/core/templates/core/courses_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
    <a href="import-csv/">Import Courses from CSV</a>
    <br />
    {{ block.super }}
{% endblock %}

app/core/templates/core/index.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %} 


{% block content %}
<h1>Your New Blank Canvas!</h1>
    <p class="fs-5 col-md-8">Create an amazing, dynamic webapp here.</p>

    <div class="mb-5">
      <a href="{% url 'core:index' %}" class="btn btn-primary btn-lg px-4">Button Example</a>
    </div>

    <hr class="col-3 col-md-2 mb-5">

    <div class="row g-5">
      <div class="col-md-6">
        <h2>Some more Html</h2>
        <p>Create some awesome content.</p>
        <ul class="icon-list ps-0">
          <li class="d-flex align-items-start mb-1"><a href="{% url 'core:index' %}">Important link</a></li>
        </ul>
      </div>
    </div>
{% endblock %} 

app/core/templates/core/students_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
    <a href="import-csv/">Bulk Update Support Plans</a>
    <br />
    {{ block.super }}
{% endblock %}

app/core/templates/core/submissions_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
    <a href="assign-markers/">Assign Markers</a>
    <br />
    {{ block.super }}
{% endblock %}